spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taxi
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: ride-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
server:
  port: 8081